from typing import List

from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    query: str = Field(..., description="The query to be processed.")
    user_key: str = Field(..., description="The key of the user making the request.")


class QueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the AI model.")
    sources: List[str] = Field(
        ..., description="List of sources used to generate the response."
    )


class User(BaseModel):
    key: str = Field(..., description="The unique key of the user.")
    first_name: str = Field(..., description="The first name of the user.")
    last_name: str = Field(..., description="The last name of the user.")
    email: str = Field(..., description="The email address of the user.")
    role: str = Field(..., description="The role of the user.")


class UserListResponse(BaseModel):
    data: List[User] = Field(..., description="List of users.")
    total: int = Field(..., description="Total number of users.")
    page: int = Field(..., description="Current page number.")
    page_size: int = Field(..., description="Number of users per page.")
