from typing import List

from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    query: str = Field(..., description="The query to be processed.")
    user_key: str = Field(..., description="The key of the user making the request.")


class QueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the AI model.")
    sources: List[str] = Field(
        ..., description="List of sources used to generate the response."
    )
